/* Generated By:JavaCC: Do not edit this line. Lexer2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int SL_COMMENT = 2;
  /** RegularExpression Id. */
  int BLK_COMMENT = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int STATIC = 8;
  /** RegularExpression Id. */
  int PUBLIC = 9;
  /** RegularExpression Id. */
  int MAIN = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int DOUBLE = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int THIS = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int SYSTEM = 24;
  /** RegularExpression Id. */
  int OUT = 25;
  /** RegularExpression Id. */
  int PRINTLN = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int LETTER = 28;
  /** RegularExpression Id. */
  int INTEGER = 29;
  /** RegularExpression Id. */
  int OCTAL = 30;
  /** RegularExpression Id. */
  int HEXADECIMAL = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int INTLIT = 33;
  /** RegularExpression Id. */
  int DBLLIT = 34;
  /** RegularExpression Id. */
  int STRLIT = 35;
  /** RegularExpression Id. */
  int ADD = 36;
  /** RegularExpression Id. */
  int SUB = 37;
  /** RegularExpression Id. */
  int MUL = 38;
  /** RegularExpression Id. */
  int DIV = 39;
  /** RegularExpression Id. */
  int AND = 40;
  /** RegularExpression Id. */
  int OR = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int EQ = 43;
  /** RegularExpression Id. */
  int NE = 44;
  /** RegularExpression Id. */
  int LT = 45;
  /** RegularExpression Id. */
  int LE = 46;
  /** RegularExpression Id. */
  int GT = 47;
  /** RegularExpression Id. */
  int GE = 48;
  /** RegularExpression Id. */
  int ASSGN = 49;
  /** RegularExpression Id. */
  int SEMI = 50;
  /** RegularExpression Id. */
  int COMMA = 51;
  /** RegularExpression Id. */
  int DOT = 52;
  /** RegularExpression Id. */
  int LPAREN = 53;
  /** RegularExpression Id. */
  int RPAREN = 54;
  /** RegularExpression Id. */
  int LBRAC = 55;
  /** RegularExpression Id. */
  int RBRAC = 56;
  /** RegularExpression Id. */
  int LCURLY = 57;
  /** RegularExpression Id. */
  int RCURLY = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<SL_COMMENT>",
    "\"/*\"",
    "<token of kind 4>",
    "\"*/\"",
    "\"class\"",
    "\"extends\"",
    "\"static\"",
    "\"public\"",
    "\"main\"",
    "\"void\"",
    "\"boolean\"",
    "\"int\"",
    "\"double\"",
    "\"String\"",
    "\"true\"",
    "\"false\"",
    "\"new\"",
    "\"this\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"System\"",
    "\"out\"",
    "\"println\"",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER>",
    "<OCTAL>",
    "<HEXADECIMAL>",
    "<ID>",
    "<INTLIT>",
    "<DBLLIT>",
    "<STRLIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 59>",
  };

}
