/* Generated By:JavaCC: Do not edit this line. Lexer2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LTTR = 4;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int SUB = 6;
  /** RegularExpression Id. */
  int ASSGN = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int LT = 9;
  /** RegularExpression Id. */
  int LE = 10;
  /** RegularExpression Id. */
  int RT = 11;
  /** RegularExpression Id. */
  int RE = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int SL = 14;
  /** RegularExpression Id. */
  int SLE = 15;
  /** RegularExpression Id. */
  int SR = 16;
  /** RegularExpression Id. */
  int SRE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<LTTR>",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"\\n\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>\"",
    "\">>=\"",
  };

}
