/* Generated By:JavaCC: Do not edit this line. Lexer2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int SLCMT = 6;
  /** RegularExpression Id. */
  int BLKCMT = 8;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<ID>",
    "<SLCMT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
  };

}
