/* Generated By:JavaCC: Do not edit this line. Stmt1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Stmt1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int IntLit = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "\"print\"",
    "<ID>",
    "<IntLit>",
    "\"=\"",
    "\";\"",
  };

}
