/* Generated By:JavaCC: Do not edit this line. Stmt3Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Stmt3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int ID = 7;
  /** RegularExpression Id. */
  int IntLit = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "<ID>",
    "<IntLit>",
    "\".\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
