/* Generated By:JavaCC: Do not edit this line. Lexer2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int ALTER = 5;
  /** RegularExpression Id. */
  int REPEAT = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int ONEMORE = 11;
  /** RegularExpression Id. */
  int ZEROONE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<LETTER>",
    "\"|\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "<DIGIT>",
    "\"+\"",
    "\"?\"",
  };

}
